version: '3'

services: 
  backend:
    build: 
      context: backend
    container_name: Backend
    ports: 
      - "8080:8080"

  frontend:
    build: 
      context: frontend
      target: build
    container_name: Frontend
    volumes: 
      - frontend_build:/app/dist
    command : sh -c "cp -r /app/dist/* /output"
    depends_on:
      - backend
  caddy:
    image: caddy:latest
    container_name: Caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - frontend_build:/srv
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on :
      - frontend
volumes:
  frontend_build :
  caddy_data:
  caddy_config:
   

